### ISSUE TITLE
Tests are broken with Yarn 4

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#299]
```
Run ddev task assets
[assets] ➤ YN0000: · Yarn 4.0.0
[assets] ➤ YN0000: ┌ Resolution step
[assets] ➤ YN0000: └ Completed
[assets] ➤ YN0000: ┌ Fetch step
[assets] ➤ YN0000: └ Completed
[assets] ➤ YN0000: ┌ Link step
[assets] ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
[assets] ➤ YN0000: └ Completed
[assets] ➤ YN0000: · Done with warnings in 0s 506ms
[sass:compile] node:internal/modules/cjs/loader:1077
[sass:compile]   const err = new Error(message);
[sass:compile]               ^
[sass:compile] 
[sass:compile] Error: Cannot find module 'gulp'
[sass:compile] Require stack:
[sass:compile] - /mnt/ddev-global-cache/yarn/berry/@lullabot-drainpipe-sass-npm-0.1.1-97dbcf6ed2-10c0.zip/node_modules/@lullabot/drainpipe-sass/gulp.js
[sass:compile] Require stack:
[sass:compile] - /mnt/ddev-global-cache/yarn/berry/@lullabot-drainpipe-sass-npm-0.1.1-97dbcf6ed2-10c0.zip/node_modules/@lullabot/drainpipe-sass/gulp.js
[sass:compile]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[sass:compile]     at require$$0.Module._resolveFilename (/var/www/html/.pnp.cjs:11469:54)
[sass:compile]     at Module._load (node:internal/modules/cjs/loader:922:27)
[sass:compile]     at require$$0.Module._load (/var/www/html/.pnp.cjs:11383:31)
[sass:compile]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[sass:compile]     at require (node:internal/modules/cjs/helpers:121:18)
[sass:compile]     at Object.<anonymous> (/mnt/ddev-global-cache/yarn/berry/@lullabot-drainpipe-sass-npm-0.1.1-97dbcf6ed2-10c0.zip/node_modules/@lullabot/drainpipe-sass/gulp.js:1:14)
[sass:compile]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[sass:compile]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[sass:compile]     at require$$0.Module._extensions..js (/var/www/html/.pnp.cjs:11535:33) {
[sass:compile]   code: 'MODULE_NOT_FOUND'
[sass:compile] }
[sass:compile] 
[sass:compile] Node.js v18.17.1
task: Failed to run task "assets": exit status 1
Failed to run task assets: exit status 201
Error: Process completed with exit code 1.
```

```
Run ddev yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/4.0.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.0.0.cjs
➤ YN0000: Done in 0s 594ms
➤ YN0000: · Yarn 4.0.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 115ms
➤ YN0000: · Yarn 4.0.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @lullabot/nightwatch-drupal-commands@npm:1.0.1, nightwatch-axe-verbose@npm:2.2.2, nightwatch@npm:3.2.1, @assemblyscript/loader@npm:0.10.1, and 420 more.
➤ YN0000: └ Completed in 4s 546ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 423 packages were added to the project (+ 206.38 MiB).
➤ YN0000: └ Completed in 10s 102ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @nightwatch/nightwatch-inspector@npm:1.0.1 must be built because it never has been before or the last one failed
➤ YN0007: │ nice-napi@npm:1.0.2 must be built because it never has been before or the last one failed
➤ YN0009: │ nice-napi@npm:1.0.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b50b6e68/build.log)
➤ YN0009: │ @nightwatch/nightwatch-inspector@npm:1.0.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-816956a8/build.log)
➤ YN0007: │ nightwatch@npm:3.2.1 [597d1] must be built because it never has been before or the last one failed
➤ YN0009: │ nightwatch@npm:3.2.1 [597d1] couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2285f3b5/build.log)
➤ YN0000: └ Completed in 3s 621ms
➤ YN0000: · Failed with errors in 18s 422ms
Failed to run yarn add nightwatch nightwatch-axe-verbose @lullabot/nightwatch-drupal-commands --dev: exit status 1
Error: Process completed with exit code 1.
```

**Comment by deviantintegral** [comment]
I think this is done now? While the merge commit failed, it appears to be unrelated: https://github.com/Lullabot/drainpipe/actions/runs/7934804633/job/21666549386

```
[deploy:git] Cloning into '/tmp/tmp.aahyVsQ7dt'...
[deploy:git] Reset branch 'main'
[deploy:git] M	composer.json
[deploy:git] Your branch is up to date with 'origin/main'.
[deploy:git] remote: Support for password authentication was removed on August 13, 2021.
[deploy:git] remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
[deploy:git] fatal: Authentication failed for 'https://github.com/lullabot/drainpipe-dev.git/'
task: Failed to run task "deploy:git": exit status 128
Failed to execute command ./vendor/bin/task deploy:git directory=/var/www/html/drainpipe/drainpipe-dev branch=main remote=***github.com/lullabot/drainpipe-dev.git message="#299 Add Yarn 4 to tests (#383)": exit status 201
Error: Process completed with exit code 1.
```

**Comment by justafish** [comment]
The test failure is due to #428
