### ISSUE TITLE
yarn lerna publish is broken

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#461]
```
❯ yarn lerna publish

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Required package missing from disk. If you keep your packages inside your repository then restarting the Node process may be enough. Otherwise, try to run an install first.

Missing package: lerna@npm:4.0.0
Expected package location: /cache/others/berry/cache/lerna-npm-4.0.0-1d3a89023c-10c0.zip/node_modules/lerna/

    at makeError (/home/justafish/repos/drainpipe/.pnp.cjs:16221:34)
    at resolveUnqualified (/home/justafish/repos/drainpipe/.pnp.cjs:17974:17)
    at resolveRequest (/home/justafish/repos/drainpipe/.pnp.cjs:18025:14)
    at Object.resolveRequest (/home/justafish/repos/drainpipe/.pnp.cjs:18081:26)
    at resolve$1 (file:///home/justafish/repos/drainpipe/.pnp.loader.mjs:1997:21)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v21.4.0
```

**Comment by justafish** [comment]
Fixed, released, and documentation added

**Comment by mrdavidburns** [comment]
I was able to replicate @davereid's error on a client project that is using Drainpipe v3.8.1
* https://github.com/Lullabot/drainpipe/issues/560#issuecomment-2250697326

From my understanding of what I've seen on most LSM client projects this is not a command we run and is instead something specific for publishing Drainpipe packages based on the documentation I'm reading.
https://github.com/Lullabot/drainpipe/blob/ad02cda93b02989f41ddf89c4414dff498803c7e/docs/metapackages.md?plain=1#L27

1. Can you explain to me the right place to be testing this?
2. If I'm testing this am I risking pushing something that isn't intended and could break something?

**Comment by justafish** [comment]
Let's keep this in #560
